# Generated by Django 2.2.7 on 2020-01-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='instrument',
        ),
    ]
