# Generated by Django 3.0.2 on 2020-01-20 16:29

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateTimeField(default=datetime.datetime.now)),
                ('close_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('open_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('result', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('direction', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=5)),
                ('open', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.FX')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.Stock')),
            ],
            options={
                'db_table': 'positions',
            },
        ),
    ]
