# Generated by Django 3.0.2 on 2020-01-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='hex_code',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='html_symbol',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='unicode_char',
        ),
    ]
