# Generated by Django 2.2.7 on 2019-12-24 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favourites',
        ),
    ]
