# Generated by Django 2.2.7 on 2019-12-11 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Account')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Stock')),
            ],
            options={
                'db_table': 'favourites',
                'unique_together': {('account', 'stock')},
            },
        ),
    ]
