# Generated by Django 2.2.7 on 2020-01-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_remove_currency_instrument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.AlterUniqueTogether(
            name='stockdata',
            unique_together={('timestamp', 'instrument')},
        ),
    ]
