# Generated by Django 3.0.2 on 2020-01-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='fx',
            name='instrument',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fx_instrument', to='trading.Instrument'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='instrument',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock_instrument', to='trading.Instrument'),
        ),
    ]
