# Generated by Django 3.0.2 on 2020-01-20 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_auto_20200120_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fx',
            name='to_currency',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='to_currency', to='trading.Currency'),
        ),
    ]
