# Generated by Django 2.2.7 on 2020-01-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_auto_20200105_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
