# Generated by Django 3.0.2 on 2020-01-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_currency_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'data_types',
            },
        ),
    ]
