# Generated by Django 3.0.2 on 2020-01-27 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_datatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxpricedata',
            name='data_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trading.DataType'),
        ),
        migrations.AddField(
            model_name='stockpricedata',
            name='data_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='trading.DataType'),
        ),
    ]
