# Generated by Django 2.2.7 on 2019-12-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_auto_20191211_1131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketData',
        ),
    ]
