# Generated by Django 3.0.2 on 2020-01-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_auto_20200120_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fx',
            old_name='favourite',
            new_name='favourite_fx',
        ),
    ]
