# Generated by Django 3.0.2 on 2020-01-28 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_auto_20200128_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base_currency',
            field=models.ForeignKey(default=91, on_delete=django.db.models.deletion.CASCADE, related_name='base_currency', to='trading.Currency'),
        ),
    ]
