# Generated by Django 3.0.2 on 2020-01-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_auto_20200128_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='funds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='account_funds'),
        ),
    ]
